Fix glsl shaders so they compile on NVIDIA (previously worked only on AMD)
I had only a AMD Radeon card in the past and these shaders worked there.
Turns out AMD's drivers are very chill but NVIDIA wasn't so happy.

Fixed following errors:
```
shader_chunk.glsl
0(49) : error C7505: OpenGL does not allow swizzles on scalar expressions
0(54) : error C7011: implicit cast from "int" to "uint"
0(55) : error C7011: implicit cast from "int" to "uint"
0(56) : error C7011: implicit cast from "int" to "uint"
0(101) : error C7549: OpenGL does not allow C style initializers
0(111) : error C7549: OpenGL does not allow C style initializers
0(130) : error C7011: implicit cast from "int" to "uint"

shader_ui.glsl
0(22) : error C7011: implicit cast from "int" to "uint"
0(23) : error C7011: implicit cast from "int" to "uint"
0(24) : error C7011: implicit cast from "int" to "uint"
0(26) : error C7011: implicit cast from "int" to "uint"
```